### PR TITLE
Expose ProtoJSONPayloadConverter marshalers and unmarshalers options

### PR DESCRIPTION
**Pull request by alexandrevilain**
## What was changed

Protojson and gogo jsonpb marshaler and umarshaler options are now public fields of the ProtoJSONPayloadConverter struct.

## Why?

It allows end-users more control on the payload converter behavior. 

I had a workflow failing caused by proto message update adding a new field. The workflow starter had the most recent version of the proto message, but not the workflow implementation. Protojson returned an `unknown field X` error which can be skipped using the `DiscardUnknown` boolean.

## Checklist

1. How was this tested:

Added unit test to ensure it does not break the default behavior of the `ProtoJSONPayloadConverter`.

### CODE REVIEW

**Comment by cretz** [comment]
I am afraid this is a bit dangerous to customize as these are default implementations that are expected to match all SDKs across all languages. I think if you need to customize the proto converters, you should create a wholly separate `PayloadConverter` with a separate encoding. This should be very easy; I can show an example if you want.

**Comment by alexandrevilain** [comment]
Hi @cretz :) 

Thanks for the review, I understand your concerns. 

IMHO, this PR isn't changing the default behavior of the `ProtoJSONPayloadConverter`, it's only providing a way for advanced users to customize the behavior without having to duplicated the whole converter logic. 

As it's instantiating empty `protojson.MarshalOptions` and `protojson.UnmarshalOptions`, it keeps the same behavior as the default `Marshal` and `Unmarshal` functions (see: https://github.com/protocolbuffers/protobuf-go/blob/v1.27.1/encoding/protojson/encode.go#L38).

**Comment by cretz** [comment]
Ability to customize the behavior is the concern. Would example code of how to make your own payload converter w/ proto options suffice instead of altering the default?

**Comment by alexandrevilain** [comment]
Thanks for your proposal. I already did my own to quick-fix the issue I had with unknown fields. 
But it's basically a copy-past of the `ProtoJSONPayloadConverter` with customizations on protojson.

I thought that it would be useful for others :)

**Comment by cretz** [comment]
> But it's basically a copy-past of the ProtoJSONPayloadConverter with customizations on protojson.

Mostly, but a tad simpler if you can assume which proto library. Here's a quick thing I threw together untested:

```go
package myconverter

import (
	"encoding/base64"
	"fmt"

	"go.temporal.io/api/common/v1"
	"go.temporal.io/sdk/converter"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type MyProtoConverter struct {
	// MetadataEncoding is required
	MetadataEncoding string
	MarshalOptions   protojson.MarshalOptions
	UnmarshalOptions protojson.UnmarshalOptions
}

var _ converter.PayloadConverter = &MyProtoConverter{}

func (m *MyProtoConverter) ToPayload(value interface{}) (*common.Payload, error) {
	// No encoding, no conversion
	if m.MetadataEncoding == "" {
		return nil, nil
	}

	// Assert type, then marshal
	p, _ := value.(proto.Message)
	if p == nil {
		return nil, nil
	}
	b, err := m.MarshalOptions.Marshal(p)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", converter.ErrUnableToEncode, err)
	}
	return &common.Payload{
		Metadata: map[string][]byte{converter.MetadataEncoding: []byte(m.MetadataEncoding)},
		Data:     b,
	}, nil
}

func (m *MyProtoConverter) FromPayload(payload *common.Payload, valuePtr interface{}) error {
	// No encoding or wrong encoding, no conversion
	if m.MetadataEncoding == "" {
		return converter.ErrEncodingIsNotSet
	} else if m.MetadataEncoding != string(payload.Metadata[converter.MetadataEncoding]) {
		return converter.ErrEncodingIsNotSupported
	}

	// Assert type, then unmarshal
	p, _ := valuePtr.(proto.Message)
	if p == nil {
		return converter.ErrTypeNotImplementProtoMessage
	}
	return m.UnmarshalOptions.Unmarshal(payload.Data, p)
}

func (*MyProtoConverter) ToString(payload *common.Payload) string {
	return base64.RawStdEncoding.EncodeToString(payload.GetData())
}

func (m *MyProtoConverter) Encoding() string {
	return m.MetadataEncoding
}
```

**Pull request closed without merging**
