### PR TITLE
[Testing] Add IsContinueAsNewError For Checking Errors in Tests

### PR DESCRIPTION
**Pull request by shannontan-bolt**
This adds a helper method to check if it is a continue as new error. I don't see any use cases aside from testing, so happy to close - or happy to put elsewhere. Made this practically copy-paste of temporal.IsCanceledError but I see that this can't exist in `temporal` for cyclic dependency reasons.

### CODE REVIEW

**Comment by vitarb** [comment]
Should we put this in the [error.go](https://github.com/temporalio/sdk-go/blob/0914229c3db0aa3dd57833681ef2d5714c20209c/temporal/error.go) instead?

**Comment by shannontan-bolt** [comment]
> Should we put this in the [error.go](https://github.com/temporalio/sdk-go/blob/0914229c3db0aa3dd57833681ef2d5714c20209c/temporal/error.go) instead?

@vitarb - it can't for the same reason that NewContinueAsNewError doesn't exist there - there's a cyclical dependency if it were to be there. At least according to the PR that moved the ContinueAsNewError to this new location.

**Comment by vitarb** [comment]
Makes sense, alright, let's keep it the way you did then.

**Review by vitarb — APPROVED** [review]

**Comment by shannontan-bolt** [comment]
@vitarb - I actually can't merge this PR since I don't have write access. Mind merging for me?

**Comment by shannontan-bolt** [comment]
@vitarb or @alexshtin - can someone merge this PR for me? Thanks!

I just keep having to update with master lol

**Pull request merged**
