### PR TITLE
Add ci trigger for sdk-features

### PR DESCRIPTION
**Pull request by Sushisource**
Draft until https://github.com/temporalio/sdk-features/pull/162 is merged

### CODE REVIEW

**Comment by Sushisource** [comment]
This is working as expected, but breakage from https://github.com/temporalio/sdk-go/pull/959 must be addressed in SDK-features

**Comment by Sushisource** [comment]
Oops, forgot to mark this one ready. The breaking change issue still stands, but we don't necessarily need to address it before merge (I also forgot to add the branch override for the go workflow, which I'll be doing soon as part of my next PR to sdk-features, so we could wait until then too).

**Review by bergundy — APPROVED** [review]

**Review by cretz — APPROVED** [review]
LGTM. We might as well get CI working even if not in this PR. It'd be a good time to test out our long-lived sdk-features temp branches for breaking changes.

**Comment by Sushisource** [comment]
I will merge this, and we can figure out the failure-fix-in-branch deal later, since this isn't set to block PRs yet.

**Pull request merged**
